### ISSUE TITLE
Renew error on QTS 5

### ISSUE THREAD

**Issue by kefflar** [Yannik/qnap-letsencrypt#113]
**Platform/Firmware Information**

```
Run
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["

Platform = X86_SKYLAKE
DISPLAY_NAME = TVS-882
Model = TS-X82
Internal Model = TS-X82
Version = 5.0.0
Build Number = 20211114
Rsync Model = QNAP
Build Date = 2021-11-14

```
Firware is Latest

Checking whether to renew certificate on Thu, 18 Nov 2021 11:40:30 +0100
Renewing certificate...
qnap-letsencrypt version: 452dc7d
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 20254
Parsing account key...
Parsing CSR...
Found domains: kefflar.pl
Getting directory...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "acme-tiny/acme_tiny.py", line 105, in get_crt
    directory, _, _ = _do_request(directory_url, err_msg="Error getting directory")
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error getting directory:
Url: https://acme-v02.api.letsencrypt.org/directory
Data: None
Response Code: None
Response: <urlopen error unknown url type: https>
An error occured. Restoring system state.
./renew_certificate.sh: line 11: 20254 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/ssl/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Starting Qthttpd services: OK

I do: 

mkdir certs
cat cacert.pem | awk 'split_after==1{n++;split_after=0} /-----END CERTIFICATE-----/ {split_after=1} {print > "certs/cert" n ".pem"}'
wget --ca-certificate cacert.pem https://raw.githubusercontent.com/ChatSecure/OpenSSL/master/tools/c_rehash
/opt/bin/perl c_rehash certs
export SSL_CERT_FILE=`pwd`/cacert.pem

and copy them to /etc/ssl/certs - but won't help :(

**Comment by Lufthummel** [comment]
I'm running into the same issue. The error is due to the standard Python  which is not compiled with SSL support. You can verify with python3 -c "import ssl; print(ssl.OPENSSL_VERSION)".
I installed Python 3.9 from QNAPClub and this one is with SSL support. For testing purposes I hardcoded the Python path in the renew_certificate script after the Python version check

PYTHON=/opt/QPython39/bin/python3

Add least the script was running successfully and certificates were created. But now the mess starts!! I can't restart the web server even if /etc/init.d/Qthttpd.sh start or restart reports ok. Whatever I tried incl. reboot didn't help. At a last resort I run /etc/init.d/init_final.sh (which resets a lot of things) and finally got the webserver up and running again.

Maybe it is due to the fact that Apache is running with user httpdusr and won't start as Admin but I've to check this. I can't see any errors in the log file and configuration is also reported as OK.

I'm helpless in the moment ...

**Comment by dofuuz** [comment]
I installed QPython3 v3.8.6.0 from Qnapclub, and ran renew_certificate.sh. 
It worked without modification. And it seems like webserver is also fine.

<details><summary>FW info</summary>

```
Model = TS-X51
Internal Model = TS-X51
Version = 5.0.0
Build Number = 20211221
Rsync Model = QNAP
Build Date = 2021-12-21
```

</details>

Python 3.5 app is not working anymore because it does not support HTTPS connection. (At least in QTS 5)

<details><summary>HTTPS urlopen log of Python 3.5 app</summary>

```
[/share/CACHEDEV1_DATA/qnap-letsencrypt] # export SSL_CERT_FILE=cacert.pem
[/share/CACHEDEV1_DATA/qnap-letsencrypt] # /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Python 3.5.2 (default, Aug 10 2016, 18:01:45)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen # Python 3
urlopen("https://google.com")>>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/urllib/request.py", line 489, in _open
    'unknown_open', req)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/urllib/request.py", line 1324, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

</details>

I think instruction should be changed to install Python from Qnapclub or Entware.

**Comment by kefflar** [comment]
I installed QPython v3.8.6.0 too and then renew_certificate.sh working.
