### ISSUE TITLE
certificate warning accessing qnap admin console

### ISSUE THREAD

**Issue by ash73** [Yannik/qnap-letsencrypt#69]
**Platform/Firmware Information**
Platform = MARVELL_6281
Model = TS-110
Internal Model = TS-119
Version = 4.2.5
Build Number = 20170413
Rsync Model = QNAP
Build Date = 2017-04-13

**Is this the latest firmware for your device?**
YES

**Issue Summary (provide relevant error messages and log output):**

qnap-letsencrypt is all working fine, it generates a certificate for my ddns address and I can access my web site hosted on the qnap. But when I try to log in to the qnap admin console via https://lan ip it says:

Firefox does not trust this site because it uses a certificate that is not valid for 192.168.1.x:8081. The certificate is only valid for myaddress.ddns.net.

I use different ports for the admin console (8081) and web server (8082), and port 443 is forwarded to 8082 on the router. I only access the admin console on the lan.

It's an old qnap, I'm not sure if the https console ever worked without a warning I only recently started using it.

Sorry this is a noob question - is it possible to get both working together? Do I need to configure letsencrypt somehow for both external and internal addresses?

TIA.

**Comment by itemx** [comment]
The things you describe is exactly how the https protocol and the certification works.
By default, letsencrypt supports single (and multiple) domains, and it does give a certification for a private (LAN) IP.

You can just ignore the warning by your browser when connect to the NAS via https: //lan . It will not gives you significant security issues in this case because nobody can pretend they are your NAS inside your LAN.
